const PRIMARY = '#000920';
const HIGHLIGHT = '#ff9500';
const BACKGROUND_INVERSE = '#555';
const DISABLED = '#666';
const TEXT = '#fff';
const TEXT_INVERSED = '#999';
const BACKGROUND = '#001259';

export {
  TEXT,
  TEXT_INVERSED,
  PRIMARY,
  HIGHLIGHT,
  DISABLED,
  BACKGROUND_INVERSE,
  BACKGROUND,
};
