const PRIMARY = '#001c47';
const HIGHLIGHT = '#ff9500';
const BACKGROUND_INVERSE = '#d8d8d8';
const DISABLED = '#8e8e93';
const TEXT = '#fff';
const TEXT_INVERSED = '#333';
const BACKGROUND = '#0082c9';

export {
  TEXT,
  TEXT_INVERSED,
  PRIMARY,
  HIGHLIGHT,
  DISABLED,
  BACKGROUND_INVERSE,
  BACKGROUND,
};
